<?php
return [
    'email_footer' => 'Ne pas envoyer de mail à cette adresse. Cet email est automatiquement envoyé par le système.',
    'login_message' => 'Veuillez vous connecter pour commencer votre session.',
    'text_forgot_password' => 'Mot de passe oublié ?',
    'page_title_login' => 'Page de connexion',
    'page_title_forgot' => 'Mot de passe oublié',
    'forgot_message' => 'Veuillez entrer votre adresse mail pour réinitialiser votre mot de passe',
    "forgot_text_try_again" => "Retente encore ?",
    'text_no_notification' => "Vous avez 0 notifications",
    'text_view_all_notification' => 'Voir toutes les notifications',
    'label_button_profile' => "Profil",
    'filter_dialog_title' => 'Tri & filtres avancés',
    'there_is_no_option' => 'Il n\'y a aucun paramètre d\'option pour ce champ',
    'no' => 'Non.',

    'text_enter_the_password' => 'Entrez votre mot de passe pour revenir sur votre session',
    'text_or_sign_in' => 'Ou connectez-vous sur un autre compte',
    'text_default_add_new_module' => 'Ajouter un nouveau :module',
    'text_default_list_module' => 'Liste :module',
    'text_default_help_password' => '5 caractéres minimum. Laissez vide si jamais vous ne voulez pas changer le mot de passe.',
    'text_default_help_upload' => 'Format supporté : JPG, JPEG, PNG, GIF, BMP',
    'text_default_help_number' => 'Chiffres uniquements',
    'text_default_help_email' => 'Entrez une adresse mail valide',
    'text_default_help_text' => 'Lettres uniquement',
    'text_default_help_url' => 'Entrez un lien valide',
    'text_dashboard' => 'Dashboard',
    'text_delete' => 'Supprimer',
    'text_prefix_option' => '** Sélectionnez un',
    'text_loading' => 'Chargement en cours...',

    'message_after_logout' => 'Merci, à plus tard !',
    'message_forgot_password' => 'Nous vous avons envoyé un mail avec votre nouveau mot de passe, regardez dans votre boîte ou dans la catégorie spam !',

    'page_not_found' => 'Oups ! Page introuvable',
    'page_not_found_text' => 'Nous ne trouvons la page que vous recherchez.',
    'page_not_found_tips' => '* Vérifier si votre lien est correct :<br/>
                * Veuillez vous assurer que la mise en majuscule de la police est correcte car sensible à la casse<br/>
                * Peut-être que la page a été supprimée par un Admin<br/>
                * Vous pouvez revenir en arrière via le bouton retour de votre navigateur<br/>',

    'log_try_view' => 'Essayer de voir les données :name dans :module',
    'log_try_edit' => 'Essayer de modifier les données :name dans :module',
    'log_try_add' => 'Essayer d\'ajouter des données dans :module',
    'log_try_add_save' => 'Essayer d\'ajouter les données :name dans :module',
    'log_try_delete' => 'Essayer de supprimer les données :name dans :module',
    'log_try_delete_selected' => 'Essayer de supprimer les données sélectionnée dans :module',
    'log_try_delete_image' => 'Essayer de supprimer l\'image :name data dans :module',
    'log_try_update' => 'Essayer de update les données :name dans :module',
    'log_add' => 'Ajouter de nouvelles données :name dans :module',
    'log_update' => 'Update les données :name dans :module',
    'log_delete' => 'Supprimer les données :name dans :module',
    'log_delete_image' => 'Supprimer l\'image :name dans :module',
    'log_login' => ':email connecté avec l\'adresse IP : :ip',
    'log_forgot' => 'Une personne sous l\'adresse IP :ip a fait une demande de nouveau mot de passe pour :email',
    'log_logout' => ':email déconnecté',

    'alert_delete_selected' => 'Êtes-vous sûr de supprimer les données selectionnées ? ?',
    'alert_delete_selected_success' => 'Données supprimées avec succès !',
    'alert_bulk_action_button' => 'Êtes-vous sûr de',
    'alert_action' => 'Vous avez :action avec succès !',
    'alert_add_data_success' => 'L\'élément a été ajouté avec succès !',
    'alert_add_data_failed' => 'Erreur dans l\'enregistrement des données !',
    'alert_update_data_success' => 'L\'élément a bien été mis à jour !',
    'alert_update_data_failed' => 'Erreur dans la mise à jour des données !',
    'alert_delete_data_success' => 'Données supprimée avec succès !',
    'alert_want_to_logout' => 'Voulez-vous vous déconnecter ?',
    'alert_warning' => "Oups",
    'alert_danger' => 'Quelque chose s\'est mal passé....',
    'alert_success' => 'Wow, bon travail...',
    'alert_info' => 'Information',
    'alert_primary' => 'Information',
    'alert_session_expired' => 'Votre session a expiré, veuillez vous reconnecter !',
    'alert_password_wrong' => 'Votre mot de passe ne correspond pas !',
    'alert_required' => 'Veuillez vous assurer de remplir correctement tous les champs obligatoires',
    'alert_error_ajax' => 'D\'accord, c\'est embarrassant, quelque chose s\'est mal passé, nous allons le réparer bientôt !',
    'alert_validation_error' => 'Veuillez remplir correctement le formulaire : :error',
    'alert_select_a_data' => 'Veuillez sélectionner au moins un élément !',

    'add_data_page_title' => 'Ajouter :module',
    'edit_data_page_title' => 'Modifier :module',
    'detail_data_page_title' => 'Détail :module',

    'default_module_description' => 'Liste de données',

    'delete_description_confirm' => "Vous ne pourrez pas récupérer ces données !",
    'delete_title_confirm' => "Êtes-vous sûr de continuer ?",

    'action_show_data' => 'Afficher les données',
    'action_add_data' => 'Ajouter des données',
    'action_delete_selected' => 'Supprimer la sélection',

    'action_label' => 'Action',
    'action_detail_data' => 'Détail',
    'action_edit_data' => 'Modifier',
    'action_delete_data' => 'Supprimer',

    'button_cancel' => 'Annuler',
    'button_add' => 'Ajouter',
    'button_edit' => 'Modifier',
    'button_back' => 'Retour',
    'button_save' => 'Sauvegarder',
    'button_save_more' => 'Sauvegarder & Ajouter plus',
    'button_import' => 'Importer données',
    'button_export' => 'Exporter données',
    'button_filter' => 'Trier & Filtrer',
    'button_close' => 'Fermer',
    'button_submit' => 'Envoyer',
    'button_logout' => 'Déconnexion',
    'button_sign_in' => 'S\'identifier',
    'button_selected_action' => 'Actions en vrac',
    'button_download_file' => 'Téléchargier un fichier',
    'button_reset' => 'Réinitialiser',
    'button_add_to_table' => 'Ajouter au tableau',

    'export_dialog_title' => "Exporter données",
    'export_dialog_filename' => 'Nom du fichier',
    'export_dialog_help_filename' => 'Vous pouvez renommer le nom du fichier selon vos souhaits',
    'export_dialog_maxdata' => "Taille maximum",
    'export_dialog_help_maxdata' => 'Minimum 1 et maximum 100 000 lignes par session d\'exportation',
    'export_dialog_columns' => 'Colonne',
    'export_dialog_format_export' => 'Format d\'exportation',
    'export_dialog_show_advanced' => 'Afficher l\'exportation avancée',
    'export_dialog_page_size' => 'Taille de la page',
    'export_dialog_set_default' => 'Définir comme format de page par défaut',
    'export_dialog_page_orientation' => 'Orientation de la page',

    'import_page_title' => 'Importer les données de :module',
    'dashboard_default_text' => 'Bienvenue sur le dashboard de :appname',
    'form_back_to_list' => 'Retour à la liste de données de :module',
    'not_logged_in' => 'Vous n\'êtes pas connecté !',
    'menu_navigation' => "Navigation",
    'table_data_not_found' => "Données introuvables",
    "notice_delete_file_upload" => "* Si vous souhaitez télécharger un autre fichier, veuillez d'abord supprimer le fichier.",
    "file_broken" => "Oups on dirait que le fichier était cassé ! Cliquez sur supprimer et réessayer.",

    'denied_access' => 'Désolé, vous n\'avez pas la permission pour accéder à cet espace !',
    'denied_update' => 'Désolé, vous n\'avez pas la permission pour modifier ces données !',
    'denied_create' => 'Désolé, vous n\'avez pas la permission pour ajouter des données !',
    'denied_delete' => 'Désolé, vous n\'avez pas la permission pour supprimer ces données !',

    'user_image' => 'Photo d\utilisateur',
    'online' => 'En ligne',
    'controller_route_404' => 'Controller/Route introuvable',
    'home' => 'Page d\'accueil',
    'Notifications' => 'Notifications',
    'Privileges' => 'Permission',
    'Privileges_Roles' => 'Gérer les rôles',
    'Add_New_Privilege' => 'Ajouter un rôle',
    'List_Privilege' => 'Liste des rôles',
    'add_user' => 'Ajouter un utilisateur',
    'List_users' => 'Liste des utilisateurs',
    'Menu_Management' => 'Menu Management',
    'Add_New_Setting' => 'Ajouter des options',
    'Add_New_Module' => 'Ajouter des modules',
    'List_Module' => 'Liste des modules',
    'Add_New_Statistic' => 'Ajouter une nouvel statistique',
    'List_Statistic' => 'Liste des statistiques',
    'Add_New_API' => 'Ajoute une nouvelle API',
    'API_Generator' => 'API Generator',
    'Statistic_Builder' => 'Statistic Builder',
    'Module_Generator' => 'Module Generator',
    'settings' => 'Options',
    'Users_Management' => 'Gestion des utilisateurs',
    'list_API' => 'Liste des API (Documentation)',
    'Generate_Screet_Key' => 'Générer une Secret Key',
    'Add_New_Email' => 'Ajouter un nouvel Email',
    'List_Email_Template' => 'Liste des template d\'Email',
    'Email_Templates' => 'Email Templates',
    'Log_User_Access' => 'Log d\'accès utilisateurs',
    'SUPERADMIN' => 'SUPER ADMIN',

    'click_here' => 'Cliquez ici',

    /*
     * this is for html direction to use in html and css classes like :
     * pull-left , pull-right , text-right ...
     * to make it easy to use the the view for rtl langs .
     * unless your language use right-to-left direction , you should keep it as it is :
     */
    'right' => 'right',
    'left' => 'left',

    'all_rights_reserved' => 'Tous droits reservés',
    'copyright' => 'Copyright',
    'powered_by' => 'Propulsé par',

    'notification_you_have' => 'Vous avez',
    'notification_notification' => 'Notifications',
    'notification_new' => 'Vous avez de nouvelles notifications !',

    'login_register_style' => 'Apparence de la page de connexion',
    'email_setting' => 'Options de l\'adresse mail',
    'application_setting' => 'Options de la plateforme',

    // table filter & sort
    'filter_select_operator_type' => 'Select Operator Type',
    'filter_ascending' => 'ASCENDING',
    'filter_descending' => 'DESCENDING',
    'filter_equal_to' => '=(Equal to)',
    'filter_like' => 'LIKE',
    'filter_not_like' => 'NOT LIKE',
    'filter_greater_than_or_equal' => '>= (Greater Than or Equal)',
    'filter_less_than_or_equal' => '<= (Less Than or Equal)',
    'filter_less_than' => '< (Less Than)',
    'filter_greater_than' => '> (Greater Than)',
    'filter_not_equal_to' => '!= (Not Equal to)',
    'filter_in' => 'IN',
    'filter_not_in' => 'NOT IN',
    'filter_between' => 'BETWEEN',
    'filter_empty_or_null' => 'Empty ( or Null)',
    'filter_sort_ascending' => 'Sort ascending',
    'filter_sort_descending' => 'Sort Descending',
    'filter_eg' => 'e.g',
    'filter_lorem_ipsum' => 'Lorem ipsum',
    'filter_lorem_ipsum_dolor_sit' => ' Lorem,Ipsum,Dolor Sit',
    'filter_search' => 'Search',
    'filter_from' => 'from',
    'filter_to' => 'to',
    'filter_sorting' => 'Sorting',
    'filter_rows_total' => 'Total rows',
    'filter_rows_to' => 'to',
    'filter_rows_of' => 'of',

    // confirmation
    'confirmation_yes' => 'Oui !',
    'confirmation_no' => 'Non',

    //filemanager
    'chose_an_image' => 'Choissisez une image ',
    'chose_an_file' => 'Choisissez un fichier ',

    //action confirmation
    'confirmation_title' => 'Confirmation',
    'confirmation_text' => 'Veux-tu vraiment faire cette action ?',
    'confirmButtonText' => 'Oui',

    // privilege
    'privileges_name' => 'Nom du rôle',
    'privileges_super_admin' => 'Super Admin',
    'privileges_standart_user' => 'Utilisateur',
    'privileges_ID' => 'ID',
    'set_as_superadmin' => 'Définir comme Superadmin',
    'chose_theme_color_select' => '** Choisissez la couleur du thème principal',
    'chose_theme_color' => ' Thème',
    'privileges_configuration' => 'Configuration des permissions',
    'privileges_module_list_no' => 'Non.',
    'privileges_module_list_mod_names' => 'Module',
    'privileges_module_list_view' => 'Voir',
    'privileges_module_list_create' => 'Créer',
    'privileges_module_list_read' => 'Lire',
    'privileges_module_list_update' => 'Modifier',
    'privileges_module_list_delete' => 'Supprimer',

    //datamodal
    'datamodal_select' => 'Sélectionner',
    'datamodal_search_and_enter' => 'Rechercher et entrer...',
    'datamodal_enter_to_search' => 'Entrée pour rechercher',
    'datamodal_browse_data' => 'Parcourir les données',
    'datamodal_browse_file' => 'Parcourir les fichiers',

    //child
    'table_detail' => 'Détail du tableau',
    'your_file_size_is_too_big' => 'Fichier trop lourd',
    'save_changes' => 'Sauvegarde les changements',
    'please_complete_the_form' => 'Veuillez compléter le formulaire !',
    'this_field_is_required' => 'Ce champ est requis',
    'text_form' => 'Formulaire',
    "your_file_extension_is_not_allowed " => "Votre extension de fichier n'est pas autorisée !",
];
